[package]
name = "deltakernel"
authors.workspace = true
edition.workspace = true
homepage.workspace = true
license.workspace = true
repository.workspace = true
readme.workspace = true
version.workspace = true

[lib]
crate-type = ["cdylib", "staticlib", "rlib"]

[dependencies]
arrow-array = { version = "^46.0" }
arrow-arith = { version = "^46.0" }
arrow-json = { version = "^46.0" }
arrow-ord = { version = "^46.0" }
arrow-schema = { version = "^46.0" }
arrow-select = { version = "^46.0" }
bytes = "1.4"
chrono = { version = "0.4", optional = true }
either = "1.8"
fix-hidden-lifetime-bug = "0.2"
itertools = "0.11"
lazy_static = "1.4"
# need to generalize over arrow, arrow2 and diff parquet etc. (BYOP)
regex = "1.8"
roaring = "0.10.1"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
thiserror = "1"
# only for structured logging
tracing = "0.1"
url = "2"
uuid = "1.3.0"
z85 = "3.0.5"

# used for developer-visibility
visibility = "0.1.0"

# Used in default client
futures = { version = "0.3", optional = true }
object_store = { version = "^0.7.0", optional = true }
parquet = { version = "^46.0", optional = true, features=["async", "object_store"]}

# optionally used with default client (though not required)
tokio = { version = "1", optional = true, features=["rt-multi-thread"] }

# for the cffi
libc = "0.2.147"

[features]
default = ["default-client"]
default-client = ["chrono", "futures", "object_store", "parquet"]
developer-visibility = []

[dev-dependencies]
arrow = { version = "^46.0", features = ["json", "prettyprint"] }
deltakernel = { path = ".", features = ["tokio"] }
test-log = { version = "0.2", default-features = false, features = ["trace"] }
tempfile = "3"
test-case = { version = "3.1.0" }
tokio = { version = "1" }
tracing-subscriber = { version = "0.3", default-features = false, features = [
  "env-filter",
  "fmt",
] }
